// Code generated by Wire protocol buffer compiler, do not edit.
// Source: tsuyoyo.protobuf.demo.Author in book.proto
package tsuyoyo.protobuf.demo

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Unit
import kotlin.jvm.JvmField
import okio.ByteString

public class Author(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
  )
  public val id: Int = 0,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
  )
  public val name: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
  )
  public val penName: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<Author, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  public override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Author) return false
    if (unknownFields != other.unknownFields) return false
    if (id != other.id) return false
    if (name != other.name) return false
    if (penName != other.penName) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + id.hashCode()
      result = result * 37 + name.hashCode()
      result = result * 37 + penName.hashCode()
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    result += """id=$id"""
    result += """name=${sanitize(name)}"""
    result += """penName=${sanitize(penName)}"""
    return result.joinToString(prefix = "Author{", separator = ", ", postfix = "}")
  }

  public fun copy(
    id: Int = this.id,
    name: String = this.name,
    penName: String = this.penName,
    unknownFields: ByteString = this.unknownFields,
  ): Author = Author(id, name, penName, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<Author> = object : ProtoAdapter<Author>(
      FieldEncoding.LENGTH_DELIMITED, 
      Author::class, 
      "type.googleapis.com/tsuyoyo.protobuf.demo.Author", 
      PROTO_3, 
      null, 
      "book.proto"
    ) {
      public override fun encodedSize(`value`: Author): Int {
        var size = value.unknownFields.size
        if (value.id != 0) size += ProtoAdapter.INT32.encodedSizeWithTag(1, value.id)
        if (value.name != "") size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.name)
        if (value.penName != "") size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.penName)
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: Author): Unit {
        if (value.id != 0) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.id)
        if (value.name != "") ProtoAdapter.STRING.encodeWithTag(writer, 2, value.name)
        if (value.penName != "") ProtoAdapter.STRING.encodeWithTag(writer, 3, value.penName)
        writer.writeBytes(value.unknownFields)
      }

      public override fun encode(writer: ReverseProtoWriter, `value`: Author): Unit {
        writer.writeBytes(value.unknownFields)
        if (value.penName != "") ProtoAdapter.STRING.encodeWithTag(writer, 3, value.penName)
        if (value.name != "") ProtoAdapter.STRING.encodeWithTag(writer, 2, value.name)
        if (value.id != 0) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.id)
      }

      public override fun decode(reader: ProtoReader): Author {
        var id: Int = 0
        var name: String = ""
        var penName: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> id = ProtoAdapter.INT32.decode(reader)
            2 -> name = ProtoAdapter.STRING.decode(reader)
            3 -> penName = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return Author(
          id = id,
          name = name,
          penName = penName,
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: Author): Author = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<Author> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
