// Code generated by Wire protocol buffer compiler, do not edit.
// Source: tsuyoyo.protobuf.demo.Genre in book.proto
package tsuyoyo.protobuf.demo

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import kotlin.Int
import kotlin.jvm.JvmField
import kotlin.jvm.JvmStatic

public enum class Genre(
  public override val `value`: Int,
) : WireEnum {
  UNKNOWN(0),
  SCIENCE(1),
  FANTASY(2),
  MYSTERY(3),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<Genre> = object : EnumAdapter<Genre>(
      Genre::class, 
      PROTO_3, 
      Genre.UNKNOWN
    ) {
      public override fun fromValue(`value`: Int): Genre? = Genre.fromValue(value)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): Genre? = when (value) {
      0 -> UNKNOWN
      1 -> SCIENCE
      2 -> FANTASY
      3 -> MYSTERY
      else -> null
    }
  }
}
